#!/bin/bash

LOG=/tmp/stack.log

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

TOMCAT_URL=http://www.mirrorservice.org/sites/ftp.apache.org/tomcat/tomcat-9/v9.0.14/bin/apache-tomcat-9.0.14.tar.gz
TOMCAT_TAR_FILE=$(echo $TOMCAT_URL | cut -d / -f10)
TOMCAT_HOME=$(echo $TOMCAT_TAR_FILE | sed -e 's/.tar.gz//g')
MOD_JK_URL=http://apache.mirrors.nublue.co.uk/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.46-src.tar.gz
MOD_JK_TAR=$(echo $MOD_JK_URL | cut -d / -f7)
MOD_JK_HOME=$(echo $MOD_JK_TAR | sed -e 's/.tar.gz//g')
MYSQL_URL=https://github.com/devops2k18/DevOpsAug/raw/master/APPSTACK/mysql-connector-java-5.1.40.jar
MYSQL_HOME=$( echo $MYSQL_URL | cut -d / -f9 )
STUDENT_WAR_URL=https://github.com/devops2k18/DevOpsAug/raw/master/APPSTACK/student.war


VALIDATE(){
	if [ $1 -ne 0 ]; then
		echo -e "$2 ... $R FAILED $N"
		exit 1
	else	
		echo -e "$2 ... $G SUCCESS $N"
	fi
}

SKIP() {
	echo -e "$1 .... $Y skiping $N"

}
yum install httpd -y &>>$LOG

#Installing Webserver


VALIDATE $? "Installing Webserever"

systemctl start httpd &>>$LOG  

VALIDATE $? "Starting httpd"

systemctl enable httpd &>>$LOG

VALIDATE $? "Enabling httpd"

if [ -f "/root/$MOD_JK_TAR" ]; then 
	SKIP "Installing MOD_JK"
else
	wget $MOD_JK_URL -O "/root/$MOD_JK_TAR" &>>$LOG
	VALIDATE $? "Installing MOD_JK"
fi 

cd /root
if [ -d "/root/$MOD_JK_HOME" ]; then 
	SKIP "Extracting MOD_JK"
else
	tar -xf "$MOD_JK_TAR" &>>$LOG
	VALIDATE $? "Extracting MOD_JK"
fi

cd $MOD_JK_HOME/native

yum install gcc httpd-devel -y &>>$LOG

VALIDATE $? "Installing gcc httpd-devel"

if [ -f "/etc/httpd/modules/mod_jk.so" ]; then
	SKIP "Compiling MOD_JK"
else
	./configure --with-apxs=/bin/apxs &>>$LOG && make &>>$LOG && make install &>>$LOG
	 VALIDATE $? "Compiling & installing MOD_JK"
fi

cd /etc/httpd/conf.d

if [ -f "modjk.conf" ]; then
	SKIP "creating modjk.conf"
else
	echo	'LoadModule jk_module modules/mod_jk.so
			JkWorkersFile conf.d/workers.properties
			JkLogFile logs/mod_jk.log
			JkLogLevel info
			JkLogStampFormat "[%a %b %d %H:%M:%S %Y]"
			JkOptions +ForwardKeySize +ForwardURICompat -ForwardDirectories
			JkRequestLogFormat "%w %V %T"
			JkMount /student tomcatA
			JkMount /student/* tomcatA' > modjk.conf
			VALIDATE $? "Creating modjk.conf"

fi

if [ -f "workers.properties" ]; then
	SKIP "Creating workers.properties"
else
	echo '### Define workers
	worker.list=tomcatA
	### Set properties
	worker.tomcatA.type=ajp13
	worker.tomcatA.host=localhost
	worker.tomcatA.port=8009' > workers.properties
	VALIDATE $? "Creating workers.properties"
fi 


systemctl restart httpd &>>$LOG

VALIDATE $? "Restarting httpd"


## TOMCAT App server installation


yum install java -y &>>$LOG

VALIDATE $? "Installing JAVA"

cd /root

if [ -f "$TOMCAT_TAR_FILE" ]; then
	SKIP "Installing Apache Tomcat"
else
	wget $TOMCAT_URL  &>>$LOG
	VALIDATE $? "Installing Apache Tomcat"
fi

if [ -d "$TOMCAT_HOME" ]; then
	SKIP "Extracting Apache Tomcat"
else 
	tar -xf "$TOMCAT_TAR_FILE" &>>$LOG
	VALIDATE $? "Extracting Apache Tomcat"
fi

cd "$TOMCAT_HOME/conf"

sed -i -e '/TestDB/ d' context.xml

sed -i -e '$ i <Resource name="jdbc/TestDB" auth="Container" type="javax.sql.DataSource" maxTotal="100" maxIdle="30" maxWaitMillis="10000" username="student" password="student@1" driverClassName="com.mysql.jdbc.Driver" url="jdbc:mysql://localhost/studentapp"/>' context.xml

VALIDATE $? "Adding DB config to context.xml"

## Downloading db connectors in lib directory

cd ../lib

if [ -f $MYSQL_HOME ]; then
	SKIP "Downloading mysql connector"
else
	wget $MYSQL_URL &>>$LOG
	VALIDATE $? "Downloading mysql connector"
fi

cd ../webapps

rm -rf *

wget $STUDENT_WAR_URL &>>$LOG

cd ../bin

sh shutdown.sh &>>$LOG

sh startup.sh &>>$LOG

VALIDATE $? "Restarting TOMCAT"

## Installing DB server##

yum install mariadb mariadb-server -y &>>$LOG
VALIDATE $? "Installing maria db"

systemctl start mariadb

VALIDATE $? "starting Maria db"

echo "create database if not exists studentapp;
use studentapp;
CREATE TABLE if not exists Students(student_id INT NOT NULL AUTO_INCREMENT,
	student_name VARCHAR(100) NOT NULL,
    student_addr VARCHAR(100) NOT NULL,
	student_age VARCHAR(3) NOT NULL,
	student_qual VARCHAR(20) NOT NULL,
	student_percent VARCHAR(10) NOT NULL,
	student_year_passed VARCHAR(10) NOT NULL,
	PRIMARY KEY (student_id)
);
grant all privileges on studentapp.* to 'student'@'localhost' identified by 'student@1';" > /tmp/student.sql

mysql < /tmp/student.sql


